export const ICONS = [
  { id: "cloud", src: "/cloud.png", alt: "cloud" },
  { id: "spark", src: "/spark.png", alt: "spark" },
  { id: "wave", src: "/wave.png", alt: "wave" },
  { id: "stone", src: "/stone.png", alt: "stone" },
  { id: "tree", src: "/tree.png", alt: "tree" },
  { id: "moon", src: "/moon.png", alt: "moon" },
  { id: "fire", src: "/fire.png", alt: "fire" },
  { id: "books", src: "/books.png", alt: "books" },
  { id: "candle", src: "/candle.png", alt: "candle" },
  { id: "coffee", src: "/coffee.png", alt: "coffee" },
  { id: "flower", src: "/flower.png", alt: "flower" },
  { id: "leaf", src: "/leaf.png", alt: "leaf" },
  // { id: "sparkle", src: "/sparkle.png", alt: "sparkle" },
  // { id: "twinkle", src: "/twinkle.png", alt: "twinkle" },
  // { id: "iced-coffee", src: "/iced-coffee.png", alt: "iced coffee" },
];
